### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by gislenius** [28msec/cellstore#802]
[hq.secxbrl.info-dev3] Serving files from: app

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at module.exports.plugin (/Code/github/cellstore/node_modules/browser-sync/lib/server/index.js:46:30)
    at null.<anonymous> (/Code/github/cellstore/node_modules/browser-sync/lib/services.js:36:68)
    at null.<anonymous> (/Code/github/cellstore/node_modules/browser-sync/lib/browser-sync.js:177:28)
    at /Code/github/cellstore/node_modules/browser-sync/lib/browser-sync.js:191:13
    at asyncCallback (dns.js:68:16)

**Comment by wcandillon** [comment]
@gislenius Could you provide more context on why this error happen and what you would expect as a result?

**Comment by gislenius** [comment]
Hi William,

It's not about the error. It's about the fact that gulp crashes instead of
just outputting it and continuing to run.

Kind regards,
Ghislain


On Fri, Mar 13, 2015 at 4:50 PM, William Candillon <notifications@github.com

**Comment by wcandillon** [comment]
@gislenius Why would you expect it to continue running?

**Comment by gislenius** [comment]
@wcandillon Some errors are not fatal errors, and it's more convenient to not have to rerun gulp server every time it happens.

**Comment by wcandillon** [comment]
@gislenius Yes and you reported #664 which makes sense. It hasn't been fixed yet because as far as I investigated with gulp it doesn't seem trivial to do. In this particular scenario however, gulp stopping seems to be the appropriate behaviour. Please feel free to re-open if I'm misunderstanding the issue.
